title = "הבלוג של י.ב.ג."
name = "YBloGeva"
# publishdir = "public/he"
# BaseURL = "http://localhost:1313/hindex.html"
license = "Creative Commons Attribution 4.0 International"
licenselink = "https://creativecommons.org/licenses/by/4.0/"
description = "לגלות את העולם הפנימי"
tags = ["", "ללא פרוטוקול", "מכשיר למכשיר", "ללא חומה"]
features = ["בלוג", "גלריה"]
canonifyurls = true
contentdir = "hcontent"
staticdir = "../static"
ThemesDir = "../themes"
alternatelangs = true

[author]
    name = "יצחק בר-גבע"

[params]
  HomePage = "hindex.html"
  nextHomePage = "eindex.html"
  nextlanguagetext = "אנגלית"
  Author = "יצחק ב.ג."
  DateForm = "Mon, 2 Jan 2006"
  Facebook = "yitzhakbg"
  Twitter = "yitzhakbg"
  Github = "yitzhakbg"
  ShowRelatedPost = true
  Disqus = "Your Disqus."
  SyntaxHighlightTheme = "solarized_dark.min.css"
  sidebartitle = "י.ב.ג."
  sidebartagline = "מבט מבפנים"
  pygmentsUseClasses = true
  banner = "images/celestial-neighbors-half.jpg"
  bannerfill = true
  totop = true
  lang = "he"

[permalinks]
  post = "/:year/:month/:day/:title/"
  # tech = "/he/:title/"

[[menu.main]]
    name = "About"
    URL = "/habout"

[[menu.main]]
    name = "Tech Blog"
    URL = "/techni"

[[menu.language]]
  pre = "<span class='pure-img' style=\"width: 50px; height: 29px; background-image: url('/images/EnglishLangFlag_50.png'); display:block\" />"
  URL = "eindex.html"
  identifier = "אנגלית"

[[menu.social]]
    pre = "<i class='fa fa-twitter'></i>"
    URL = "http://www.twitter.com/yitzhakbg"
    identifier = "twitter"

[[menu.social]]
    pre = "<i class='fa fa-android'></i>"
    URL = "/habout"
    identifier = "ybg"

[[menu.social]]
    pre = "<i class='fa fa-linkedin-square'></i>"
    URL = "https://www.linkedin.com/in/yitzhakbg"
    identifier = "linkedin"

[[menu.footer]]
    name = "Blog"
    URL = "/article"
