title = "YBG's Blog"
name = "YBloGeva"
license = "Creative Commons Attribution 4.0 International"
licenselink = "https://creativecommons.org/licenses/by/4.0/"
description = "An excursion into YBG's inner world"
tags = ["", "Protocoless", "D2D", "nowall"]
features = ["blog", "gallery"]
canonifyurls = true
staticdir = "../static"
themesDir = "../themes"


[author]
    name = "Yitzhak Bar Geva"

[params]
  HomePage = "index.html"
  nextHomePage = "hindex.html"
  nextlanguagetext = "Hebrew"
  Author = "Yitzhak Bar Geva"
  DateForm = "Mon, 2 Jan 2006"
  Facebook = "yitzhakbg"
  Twitter = "yitzhakbg"
  Github = "yitzhakbg"
  ShowRelatedPost = true
  Disqus = "Your Disqus."
  SyntaxHighlightTheme = "solarized_dark.min.css"
  sidebartitle = "YBG"
  sidebartagline = "View from inside"
  pygmentsUseClasses = true
  banner = "images/celestial-neighbors-half.jpg"
  bannerfill = true
  totop = true

[permalinks]
  post = "/:year/:month/:day/:title/"

[[menu.language]]
  pre = "<span class='pure-img' style=\"width: 40px; height: 40px; background-image: url('/images/israeliflag_40.png'); display:block\" />"
  URL = "hindex.html"
  identifier = "Hebrew"

[[menu.main]]
    name = "About"
    URL = "/about"

[[menu.main]]
    name = "Coming Home"
    URL = "/Coming-Home"

[[menu.main]]
    name = "Israel"
    URL = "/Israel"

[[menu.main]]
    name = "Tech Blog"
    URL = "/tech"

[[menu.social]]
    pre = "<i class='fa fa-twitter'></i>"
    URL = "https://www.twitter.com/yitzhakbg"
    identifier = "twitter"

[[menu.social]]
    pre = "<i class='fa fa-android'></i>"
    URL = "/about"
    identifier = "ybg"

[[menu.social]]
    pre = "<i class='fa fa-linkedin-square'></i>"
    URL = "https://www.linkedin.com/in/yitzhakbg"
    identifier = "linkedin"

[[menu.footer]]
    name = "Blog"
    URL = "/article"

