#!/bin/bash
set -x
[ $# -eq 0 ] && { echo "Usage: $0 destination not given"; exit 1; }
[ $# -eq 1 ] && { echo "Usage: $0 baseURL not given"; exit 1; }
# Script to generate Hebrew site, rename index.xml files and their references to hindex.xml,
# rename top index.html to hindex.html then merge all into the English site.
# Result is to have both English and Hebrew cooexisting in the same branch
#

targ=$1
l1targ=/tmp/${l1}public
l2targ=/tmp/${l2}public
l1content=${l1}content
l2content=${l2}content
l1index=${l1}index
lindex=${l2}index
l1config=config${l1}.toml
l2config=config${l2}.toml

[[ ! -d ${l1content} ]] && [[ -d ${l2content} ]] && { echo "There is only one content directory. Second one missing"; exit 1; }
[[ -d ${l1content} ]] && [[ ! -d ${l2content} ]] && { echo "There is only one content directory. Second one missing"; exit 1; }

# We don't want a content directory. hcontent and econtent will each become content in turn
if [ -d content ]; then
  rm -rf content
fi

# Hebrew (first language) section

hugo --config="${l1config}" -d ${l1targ} -t ${HUGO_THEME} -b $2 # Make Hebrew site in hpublic

# Change the string "index.xml" appearing in all the files named index.* to "hindex.xml"
dir=${l1targ}
echo "dir is $dir"
find $dir -type f -name 'index.*' -exec sed -i "s/index.xml/${l1index}.xml/" {} +
# Rename all the files named index.xml hindex.*
for file in $(find $dir -type f -name index.xml); do
    mv $file $(dirname "${file}")/${l1index}.xml
done
mv $dir/{,${l1}}index.html # Rename top level index.html to hindex.html

hugo --config="${l2config}" -d ${l2targ} -t ${HUGO_THEME} -b $2 # Make English site in epublic

# Make eindex copies of index.html and index.html
cp ${l2targ}/{,${l2}}index.html && cp ${l2targ}/{,${l2}}index.xml
# Merge hpublic and epublic into target
# First English
rsync -a ${l2targ}/ $targ

# Then Hebrew (Don't need static/ twice)
rsync -a --exclude={/images/,/css/,/js/,/data/,/docs/,/slides/} ${l1targ}/ $targ
