#!/bin/bash
#
# See examples at: http://blog.ittybittyapps.com/blog/2013/09/03/git-pre-push/
#
set -x
CMD="git push --no-verify onlp" # onlp here is the remote branch name
master_branch='master'

# Check if we actually have commits to push
commits=`git log @{u}..`
if [ -z "$commits" ]; then
    echo nothing to push
    # exit 0
fi

current_branch=$(git symbolic-ref HEAD | sed -e 's,.*/\(.*\),\1,')

if [[ $current_branch = $master_branch ]]; then
    $CMD
    RESULT=$?
    if [ $RESULT -ne 0 ]; then
        echo "failed $CMD"
        exit 1
    fi
fi
exit 0
